var Hero= [
    {
        "HeroNumber": 1,
        "HeroName": "痛苦之拥",
        "Heroicpainting": "伊芙琳",
        "Money": "3",
        "SkillName": "最终抚慰：",
        "SkillState": "伊芙琳对距离她最近的三个敌人造成伤害并传送到远离他们的位置。对生命值不满的敌人造成更高的伤害。",
        "Injury": "斩杀线：65%HP 技能伤害：200 / 300 / 400",
        "Relation": "刺客",
        "Race": "恶魔",
        "HIA": "images/yxtx/5.png",
        "HeroImg": "images/yxyk/5.jpg"
    },
    {
        "HeroNumber": 2,
        "HeroName": "不祥之刃",
        "Heroicpainting": "卡特琳娜",
        "Money": "3",
        "SkillName": "死亡莲华：",
        "SkillState": "卡特琳娜化身为一道剑刃飓风对附近的敌人投射出数把匕首，对其造成伤害并且降低他们的治疗效果。",
        "Injury": "技能伤害：40 / 60 / 80",
        "Relation": "刺客",
        "Race": "帝国",
        "HIA": "images/yxtx/20.png",
        "HeroImg": "images/yxyk/20.jpg"
    },
    {
        "HeroNumber": 3,
        "HeroName": "影流之主",
        "Heroicpainting": "劫",
        "Money": "2",
        "SkillName": "影奥义！诸刃：",
        "SkillState": "劫掷出他的手里剑，对其穿越的敌人造成伤害。",
        "Injury": "技能伤害：200 / 350 / 500",
        "Relation": "刺客",
        "Race": "忍者",
        "HIA": "images/yxtx/24.png",
        "HeroImg": "images/yxyk/24.jpg"
    },
    {
        "HeroNumber": 4,
        "HeroName": "离群之刺",
        "Heroicpainting": "阿卡丽",
        "Money": "4",
        "SkillName": "我流奥义！寒影：",
        "SkillState": "阿卡丽向面前掷出苦无并造成伤害。这个技能可以暴击。",
        "Injury": "技能伤害：200 / 375 / 550",
        "Relation": "刺客",
        "Race": "忍者",
        "HIA": "images/yxtx/25.png",
        "HeroImg": "images/yxyk/25.jpg"
    },
    {
        "HeroNumber": 5,
        "HeroName": "血港鬼影",
        "Heroicpainting": "派克",
        "Money": "2",
        "SkillName": "魅影浪洄：",
        "SkillState": "派克冲刺到最远处敌人的身后，显现出一个魅影对其穿越的敌人造成眩晕效果。",
        "Injury": "技能伤害：150 / 200 / 250 眩晕时间：1.5 / 2.0 /2.5秒",
        "Relation": "刺客",
        "Race": "海盗",
        "HIA": "images/yxtx/35.png",
        "HeroImg": "images/yxyk/35.jpg"
    },
    {
        "HeroNumber": 6,
        "HeroName": "虚空掠夺者",
        "Heroicpainting": "卡兹克",
        "Money": "1",
        "SkillName": "品尝恐惧：",
        "SkillState": "卡兹克斩击距离最近的敌人，并可对孤立无援的敌人造成额外伤害。",
        "Injury": "技能伤害：150 / 250 / 350",
        "Relation": "刺客",
        "Race": "虚空",
        "HIA": "images/yxtx/43.png",
        "HeroImg": "images/yxyk/43.jpg"
    },
    {
        "HeroNumber": 7,
        "HeroName": "傲之追猎者",
        "Heroicpainting": "雷恩加尔",
        "Money": "3",
        "SkillName": "残忍无情：",
        "SkillState": "雷恩加尔跃向最弱的敌人，并对其造成额外伤害。造成伤害后雷恩加尔会获得攻击速度和暴击几率。",
        "Injury": "技能伤害：210% / 320% / 430%攻速加成：0.3 / 0.5 / 0.7",
        "Relation": "刺客",
        "Race": "狂野",
        "HIA": "images/yxtx/48.png",
        "HeroImg": "images/yxyk/48.jpg"
    },
    {
        "HeroNumber": 8,
        "HeroName": "暗裔剑魔",
        "Heroicpainting": "亚托克斯",
        "Money": "3",
        "SkillName": "暗裔利刃：",
        "SkillState": "亚托克斯劈砍他面前的区域，对于其中的敌人造成伤害。",
        "Injury": "技能伤害：250 / 600 / 950",
        "Relation": "剑士",
        "Race": "恶魔",
        "HIA": "images/yxtx/3.png",
        "HeroImg": "images/yxyk/3.jpg"
    },
    {
        "HeroNumber": 9,
        "HeroName": "疾风剑豪",
        "Heroicpainting": "亚索",
        "Money": "5",
        "SkillName": "斩钢闪：",
        "SkillState": "亚索向前出剑，对两个敌人造成伤害。第三次施放时，亚索会发出一阵强烈的旋风，对直线上的敌人造成伤害并且将其击飞。",
        "Injury": "亚索向前出剑，对两个敌人造成伤害。第三次施放时，亚索会发出一阵强烈的旋风，对直线上的敌人造成伤害并且将其击飞。",
        "Relation": "剑士",
        "Race": "浪人",
        "HIA": "images/yxtx/12.png",
        "HeroImg": "images/yxyk/12.jpg"
    },
    {
        "HeroNumber": 10,
        "HeroName": "荣耀执行官",
        "Heroicpainting": "德莱文",
        "Money": "4",
        "SkillName": "旋转飞斧：",
        "SkillState": "德莱文在下次攻击时扔出一把造成额外伤害的旋转飞斧。如果如果德莱文接住了飞斧那么会立刻准备好下一发旋转飞斧。德莱文可以同时拥有多发旋转飞斧。",
        "Injury": "技能伤害：150% / 200% / 250%",
        "Relation": "剑士",
        "Race": "帝国",
        "HIA": "images/yxtx/19.png",
        "HeroImg": "images/yxyk/19.jpg"
    },
    {
        "HeroNumber": 11,
        "HeroName": "暮光之眼",
        "Heroicpainting": "慎",
        "Money": "2",
        "SkillName": "奥义！魂佑：",
        "SkillState": "慎在自身周围创造一片区域，使其中的友军可以躲避所有攻击。",
        "Injury": "技能效果： 3 / 4 / 5",
        "Relation": "剑士",
        "Race": "忍者",
        "HIA": "images/yxtx/23.png",
        "HeroImg": "images/yxyk/23.jpg"
    },
    {
        "HeroNumber": 12,
        "HeroName": "无双剑姬",
        "Heroicpainting": "菲奥娜",
        "Money": "1",
        "SkillName": "劳伦特心眼刀：",
        "SkillState": "菲奥娜变得免疫伤害和法术。短暂的延迟后，她会击晕最近的敌人并对其造成伤害。",
        "Injury": "技能伤害：100 / 175 / 250",
        "Relation": "剑士",
        "Race": "贵族",
        "HIA": "images/yxtx/26.png",
        "HeroImg": "images/yxyk/26.jpg"
    },
    {
        "HeroNumber": 13,
        "HeroName": "海洋之灾",
        "Heroicpainting": "普朗克",
        "Money": "3",
        "SkillName": "火药桶：",
        "SkillState": "普朗克会定期放置火药桶。施放技能时，普朗克会引爆这些火药桶，对附近的敌人造成伤害",
        "Injury": "技能伤害：200 / 325 / 450",
        "Relation": "剑士",
        "Race": "海盗",
        "HIA": "images/yxtx/37.png",
        "HeroImg": "images/yxyk/37.jpg"
    },
    {
        "HeroNumber": 14,
        "HeroName": "青钢影",
        "Heroicpainting": "卡密尔",
        "Money": "1",
        "SkillName": "海克斯最后通牒：",
        "SkillState": "卡蜜尔对一名敌人造成伤害和禁锢效果，并让友军集火攻击该目标。",
        "Injury": "禁锢：4 / 5 / 6 秒 伤害：200 / 325 / 450",
        "Relation": "剑士",
        "Race": "海克斯",
        "HIA": "images/yxtx/55.png",
        "HeroImg": "images/yxyk/55.jpg"
    },
    {
        "HeroNumber": 15,
        "HeroName": "雷霆咆哮",
        "Heroicpainting": "沃利贝尔",
        "Money": "3",
        "SkillName": "雷霆利爪：",
        "SkillState": "沃利贝尔强化他的攻击，以在敌人之间弹射，并施加攻击特效。",
        "Injury": "技能效果：80% / 90% / 100%",
        "Relation": "斗士",
        "Race": "极地",
        "HIA": "images/yxtx/13.png",
        "HeroImg": "images/yxyk/13.jpg"
    },
    {
        "HeroNumber": 16,
        "HeroName": "蒸汽机器人",
        "Heroicpainting": "布里茨",
        "Money": "2",
        "SkillName": "机械飞爪：",
        "SkillState": "布里茨将最远处的敌人拉向自己并将其击飞。",
        "Injury": "技能伤害：100 / 450 / 800",
        "Relation": "斗士",
        "Race": "机器人",
        "HIA": "images/yxtx/39.png",
        "HeroImg": "images/yxyk/39.jpg"
    },
    {
        "HeroNumber": 17,
        "HeroName": "虚空遁地兽",
        "Heroicpainting": "雷克赛",
        "Money": "2",
        "SkillName": "遁地：",
        "SkillState": "雷克塞短暂潜入地下，变为不可被选中状态并且治疗自身。当雷克塞钻出地面时，她会击飞最近的敌人并对其造成伤害。",
        "Injury": "技能伤害：200 / 350 / 500",
        "Relation": "斗士",
        "Race": "虚空",
        "HIA": "images/yxtx/40.png",
        "HeroImg": "images/yxyk/40.jpg"
    },
    {
        "HeroNumber": 18,
        "HeroName": "虚空恐惧",
        "Heroicpainting": "科加斯",
        "Money": "4",
        "SkillName": "破裂：",
        "SkillState": "破裂：科加斯使目标区域破裂，对其中的敌人造成伤害和眩晕效果。",
        "Injury": "技能伤害：175 / 350 / 525击飞时间1.5秒/1.75秒/2秒",
        "Relation": "斗士",
        "Race": "虚空",
        "HIA": "images/yxtx/41.png",
        "HeroImg": "images/yxyk/41.jpg"
    },
    {
        "HeroNumber": 19,
        "HeroName": "祖安怒兽",
        "Heroicpainting": "沃里克",
        "Money": "1",
        "SkillName": "无尽束缚：",
        "SkillState": "沃里克扑向生命值最低的敌人，造成伤害和晕眩并治疗自己。",
        "Injury": "技能伤害：150 / 225 / 300",
        "Relation": "斗士",
        "Race": "狂野",
        "HIA": "images/yxtx/44.png",
        "HeroImg": "images/yxyk/44.jpg"
    },
    {
        "HeroNumber": 20,
        "HeroName": "皮城执法官",
        "Heroicpainting": "蔚",
        "Money": "3",
        "SkillName": "天霸横空烈轰：",
        "SkillState": "蔚冲向距离最远的敌人，沿途将所有敌人震开，当他接触目标时会造成伤害与击飞。",
        "Injury": "伤害：250/450/650 眩晕持续：2.0/2.5/3.0秒",
        "Relation": "斗士",
        "Race": "海克斯",
        "HIA": "images/yxtx/57.png",
        "HeroImg": "images/yxyk/57.jpg"
    },
    {
        "HeroNumber": 21,
        "HeroName": "复仇焰魂",
        "Heroicpainting": "布兰德",
        "Money": "4",
        "SkillName": "烈焰风暴：",
        "SkillState": "布兰德释放一颗可以弹射的火球，对命中的敌人造成伤害。",
        "Injury": "技能伤害：250 / 450 / 650",
        "Relation": "元素使",
        "Race": "恶魔",
        "HIA": "images/yxtx/4.png",
        "HeroImg": "images/yxyk/4.jpg"
    },
    {
        "HeroNumber": 22,
        "HeroName": "冰霜女巫",
        "Heroicpainting": "丽桑卓",
        "Money": "2",
        "SkillName": "冰封陵墓：",
        "SkillState": "丽桑卓将目标封禁在冰牢中，对附近的敌人造成伤害和减速。生命值不足一半时，丽桑卓会将自己冰封，变成不可被选中状态。",
        "Injury": "技能伤害：150 / 275/ 400",
        "Relation": "元素使",
        "Race": "极地",
        "HIA": "images/yxtx/14.png",
        "HeroImg": "images/yxyk/14.jpg"
    },
    {
        "HeroNumber": 23,
        "HeroName": "冰晶凤凰",
        "Heroicpainting": "艾尼维亚",
        "Money": "5",
        "SkillName": "冰川风暴：",
        "SkillState": "艾尼维亚引导一次大型冰风暴，对其中的敌人造成伤害和攻速减慢效果。",
        "Injury": "技能伤害：700 / 950 / 1200",
        "Relation": "元素使",
        "Race": "极地",
        "HIA": "images/yxtx/17.png",
        "HeroImg": "images/yxyk/17.jpg"
    },
    {
        "HeroNumber": 24,
        "HeroName": "狂暴之心",
        "Heroicpainting": "凯南",
        "Money": "3",
        "SkillName": "秘奥义！万雷天牢引：",
        "SkillState": "凯南在自身周围召唤出一阵风暴，对其中的敌人造成伤害和眩晕效果。",
        "Injury": "技能伤害：225/ 450 / 675",
        "Relation": "元素使",
        "Race": "约德尔人/忍者",
        "HIA": "images/yxtx/22.png",
        "HeroImg": "images/yxyk/22.jpg"
    },
    {"HeroNumber": 25,
        "HeroName": "弗雷尔卓德之心",
        "Heroicpainting": "布隆",
        "Money": "2",
        "SkillName": "坚不可摧：",
        "SkillState": "布隆举起盾牌格挡最远敌人造成的一部分伤害。",
        "Injury": "技能效果：减少伤害70% / 80% / 90%",
        "Relation": "护卫",
        "Race": "极地",
        "HIA": "images/yxtx/15.png",
        "HeroImg": "images/yxyk/15.jpg"
    },
    {
        "HeroNumber": 26,
        "HeroName": "曙光女神",
        "Heroicpainting": "蕾欧娜",
        "Money": "4",
        "SkillName": "日炎耀斑：",
        "SkillState": "日炎耀斑：蕾欧娜召唤一道太阳光束从天而降，对其内的敌人造成伤害和减速效果。其中心的敌人会被晕眩。",
        "Injury": "技能伤害：175 / 250 / 325",
        "Relation": "护卫",
        "Race": "贵族",
        "HIA": "images/yxtx/27.png",
        "HeroImg": "images/yxyk/27.jpg"
    },
    {
        "HeroNumber": 27,
        "HeroName": "圣枪游侠",
        "Heroicpainting": "卢锡安",
        "Money": "2",
        "SkillName": "冷酷追击：",
        "SkillState": "卢锡安冲刺到安全位置并且对敌人攻击两次，一次算作攻击伤害另一次算作技能伤害。",
        "Injury": "技能伤害：150/250/350",
        "Relation": "枪手",
        "Race": "贵族",
        "HIA": "images/yxtx/28.png",
        "HeroImg": "images/yxyk/28.jpg"
    },
    {
        "HeroNumber": 28,
        "HeroName": "法外狂徒",
        "Heroicpainting": "格雷福斯",
        "Money": "1",
        "SkillName": "大号铅弹：",
        "SkillState": "格雷福斯的散弹枪攻击力提升并会对附近的敌人造成溅射伤害。",
        "Injury": "技能伤害：5% / 10% / 15%",
        "Relation": "枪手",
        "Race": "海盗",
        "HIA": "images/yxtx/36.png",
        "HeroImg": "images/yxyk/36.jpg"
    },
    {
        "HeroNumber": 29,
        "HeroName": "赏金猎人",
        "Heroicpainting": "厄运小姐",
        "Money": "5",
        "SkillName": "弹幕时间：",
        "SkillState": "厄运小姐呈锥形引导并发射若干波子弹来伤害敌人。",
        "Injury": "技能伤害：800 / 1250 / 1700",
        "Relation": "枪手",
        "Race": "海盗",
        "HIA": "images/yxtx/38.png",
        "HeroImg": "images/yxyk/38.jpg"
    },
    {
        "HeroNumber": 30,
        "HeroName": "麦林炮手",
        "Heroicpainting": "崔丝塔娜",
        "Money": "1",
        "SkillName": "爆炸射击：",
        "SkillState": "崔丝塔娜在当前目标上放置一颗炸弹，在数次攻击后将其引爆，对附近的敌人造成伤害。",
        "Injury": "技能伤害： 150 / 225 / 300",
        "Relation": "枪手",
        "Race": "约德尔人",
        "HIA": "images/yxtx/49.png",
        "HeroImg": "images/yxyk/49.jpg"
    },
    {
        "HeroNumber": 31,
        "HeroName": "暴走萝莉",
        "Heroicpainting": "金克丝",
        "Money": "4",
        "SkillName": "罪恶快感：",
        "SkillState": "金克丝会在参与击杀时获得加成，第一次获得攻击速度第二次将会去出火箭并造成溅射伤害。",
        "Injury": "攻击速度加成：75%/100%/125%伤害：100/225/350",
        "Relation": "枪手",
        "Race": "海克斯科技",
        "HIA": "images/yxtx/58.png",
        "HeroImg": "images/yxyk/58.jpg"
    },
    {
        "HeroNumber": 32,
        "HeroName": "北地之怒",
        "Heroicpainting": "瑟庄妮",
        "Money": "4",
        "SkillName": "极冰寒狱：",
        "SkillState": "瑟庄妮召唤巨大的冰川风暴，在短暂的延迟后眩晕其中的敌人。",
        "Injury": "技能伤害：100 / 175 / 250 眩晕时间：2秒/4秒/6秒",
        "Relation": "骑士",
        "Race": "极地",
        "HIA": "images/yxtx/18.png",
        "HeroImg": "images/yxyk/18.jpg"
    },
    {
        "HeroNumber": 33,
        "HeroName": "诺克萨斯之手",
        "Heroicpainting": "德莱厄斯",
        "Money": "1",
        "SkillName": "大杀四方：",
        "SkillState": "德莱厄斯挥舞他的斧头，对附近的敌人造成伤害并基于他命中的敌人数量来治疗自身。",
        "Injury": "技能伤害：150 / 200 / 250",
        "Relation": "骑士",
        "Race": "帝国",
        "HIA": "images/yxtx/21.png",
        "HeroImg": "images/yxyk/21.jpg"
    },
    {
        "HeroNumber": 34,
        "HeroName": "德玛西亚之力",
        "Heroicpainting": "盖伦",
        "Money": "1",
        "SkillName": "审判：",
        "SkillState": "盖伦旋转舞动他的大剑，变得免疫技能伤害并且对附近的敌人造成伤害。",
        "Injury": "技能每秒伤害：40 /65 /90",
        "Relation": "骑士",
        "Race": "贵族",
        "HIA": "images/yxtx/29.png",
        "HeroImg": "images/yxyk/29.jpg"
    },
    {
        "HeroNumber": 35,
        "HeroName": "正义天使",
        "Heroicpainting": "凯尔",
        "Money": "5",
        "SkillName": "圣裁之刻：",
        "SkillState": "凯尔为最弱的一名友军施加护盾，使其免疫伤害。",
        "Injury": "技能效果：500 / 800 / 1100",
        "Relation": "骑士",
        "Race": "贵族",
        "HIA": "images/yxtx/31.png",
        "HeroImg": "images/yxyk/31.jpg"
    },
    {
        "HeroNumber": 36,
        "HeroName": "铁铠冥魂",
        "Heroicpainting": "莫德凯撒",
        "Money": "1",
        "SkillName": "破灭之锤：",
        "SkillState": "莫德凯撒向面前猛力砸下钉锤，对直线上两个敌人造成伤害。",
        "Injury": "技能效果：500 / 800 / 1100",
        "Relation": "骑士",
        "Race": "暗影单位",
        "HIA": "images/yxtx/32.png",
        "HeroImg": "images/yxyk/32.jpg"
    },
    {
        "HeroNumber": 37,
        "HeroName": "圣锤之毅",
        "Heroicpainting": "波比",
        "Money": "3",
        "SkillName": "持卫的裁决：",
        "SkillState": "波比挥舞她的铁锤，来伤害并击飞距离最近的敌人。",
        "Injury": "技能伤害：300 / 500 / 700",
        "Relation": "骑士",
        "Race": "约德尔人",
        "HIA": "images/yxtx/50.png",
        "HeroImg": "images/yxyk/50.jpg"
    },
    {
        "HeroNumber": 38,
        "HeroName": "惩戒之箭",
        "Heroicpainting": "韦鲁斯",
        "Money": "2",
        "SkillName": "穿刺之箭：",
        "SkillState": "韦鲁斯蓄力将箭射出，对直线上的所有敌人造成伤害。",
        "Injury": "技能伤害：300/ 550 / 800",
        "Relation": "游侠",
        "Race": "恶魔",
        "HIA": "images/yxtx/6.png",
        "HeroImg": "images/yxyk/6.jpg"
    },
    {
        "HeroNumber": 39,
        "HeroName": "寒冰射手",
        "Heroicpainting": "艾希",
        "Money": "3",
        "SkillName": "魔法水晶箭：",
        "SkillState": "艾希射出一道魔法水晶箭，晕眩第一个被击中的敌人并造成伤害。敌人越远眩晕时间越长。",
        "Injury": "技能伤害：200 / 400 / 600",
        "Relation": "游侠",
        "Race": "极地",
        "HIA": "images/yxtx/16.png",
        "HeroImg": "images/yxyk/16.jpg"
    },
    {
        "HeroNumber": 40,
        "HeroName": "暗夜猎手",
        "Heroicpainting": "薇恩",
        "Money": "1",
        "SkillName": "圣银弩箭：",
        "SkillState": "每第三次攻击，薇恩会根据敌人的最大生命值造成额外真实伤害。",
        "Injury": "技能伤害：8% / 12% / 16%",
        "Relation": "游侠",
        "Race": "贵族",
        "HIA": "images/yxtx/30.png",
        "HeroImg": "images/yxyk/30.jpg"
    },
    {
        "HeroNumber": 41,
        "HeroName": "永猎双子",
        "Heroicpainting": "千珏",
        "Money": "4",
        "SkillName": "羊灵生息：",
        "SkillState": "千珏在自身周围创造一片区域，阻止其中的友军阵亡。",
        "Injury": "技能效果： 4 / 5 / 6",
        "Relation": "游侠",
        "Race": "暗影单位",
        "HIA": "images/yxtx/34.png",
        "HeroImg": "images/yxyk/34.jpg"
    },
    {
        "HeroNumber": 42,
        "HeroName": "蜘蛛女皇",
        "Heroicpainting": "伊莉斯",
        "Money": "1",
        "SkillName": "蜘蛛形态：",
        "SkillState": "伊莉丝召唤出小蜘蛛，变形并获得生命吸取。",
        "Injury": "技能伤害：蜘蛛数量2 / 3 / 4 蜘蛛攻击力：50",
        "Relation": "换形师",
        "Race": "恶魔",
        "HIA": "images/yxtx/8.png",
        "HeroImg": "images/yxyk/8.jpg"
    },
    {
        "HeroNumber": 43,
        "HeroName": "诺克萨斯统领",
        "Heroicpainting": "斯维因",
        "Money": "5",
        "SkillName": "恶魔升华：",
        "SkillState": "斯维因转变形态，吸取附近敌人的生命值。变形结束后斯维因会对周围敌人造成伤害。",
        "Injury": "技能伤害：300 / 600 / 900 生命偷取 60% / 90% / 120%",
        "Relation": "换形师",
        "Race": "恶魔/帝国",
        "HIA": "images/yxtx/9.png",
        "HeroImg": "images/yxyk/9.jpg"
    },
    {
        "HeroNumber": 44,
        "HeroName": "龙血武姬",
        "Heroicpainting": "希瓦娜",
        "Money": "3",
        "SkillName": "魔龙降世：",
        "SkillState": "希瓦娜化身巨龙掠过天空并变身，获得攻击伤害和射程。在变形期间，希瓦娜的攻击会点燃敌人。",
        "Injury": "技能伤害：100 / 150 / 200",
        "Relation": "换形师",
        "Race": "龙族",
        "HIA": "images/yxtx/10.png",
        "HeroImg": "images/yxyk/10.jpg"
    },
    {
        "HeroNumber": 45,
        "HeroName": "狂野女猎手",
        "Heroicpainting": "奈德丽",
        "Money": "1",
        "SkillName": "野性奔腾：",
        "SkillState": "奈德丽治疗自身和伤势最重的友军，然后变形并获得攻击伤害。",
        "Injury": "技能效果：20 / 70 / 120",
        "Relation": "换形师",
        "Race": "狂野",
        "HIA": "images/yxtx/45.png",
        "HeroImg": "images/yxyk/45.jpg"
    },
    {
        "HeroNumber": 46,
        "HeroName": "迷失之牙",
        "Heroicpainting": "纳尔",
        "Money": "4",
        "SkillName": "呐啊：",
        "SkillState": "纳尔变形，获得生命值、攻击伤害并跳到距离最远的敌人身后，伤害并向后猛推附近的敌人。",
        "Injury": "技能伤害：200 / 300 / 400",
        "Relation": "换形师",
        "Race": "约德尔人/狂野",
        "HIA": "images/yxtx/46.png",
        "HeroImg": "images/yxyk/46.jpg"
    },
    {
        "HeroNumber": 47,
        "HeroName": "未来守护者",
        "Heroicpainting": "杰斯",
        "Money": "2",
        "SkillName": "变形墨丘利之炮：",
        "SkillState": "杰斯击退近战距离内的一名敌人，造成伤害眩晕，随后切换形态提升攻击距离到3格并获得攻速提升攻击次数。",
        "Injury": "伤害：200/350/500眩晕：2.5/4.25/6秒攻击次数：3/5/7",
        "Relation": "换形师",
        "Race": "海克斯",
        "HIA": "images/yxtx/56.png",
        "HeroImg": "images/yxyk/56.jpg"
    },
    {
        "HeroNumber": 48,
        "HeroName": "堕落天使",
        "Heroicpainting": "莫甘娜",
        "Money": "3",
        "SkillName": "灵魂镣铐：",
        "SkillState": "莫甘娜为附近的敌人套上枷锁并造成伤害。如果在短暂的延迟后敌人依然在附近则会被眩晕。",
        "Injury": "技能伤害：200 / 325 / 450",
        "Relation": "法师",
        "Race": "恶魔",
        "HIA": "images/yxtx/7.png",
        "HeroImg": "images/yxyk/7.jpg"
    },
    {
        "HeroNumber": 49,
        "HeroName": "铸星龙王",
        "Heroicpainting": "奥瑞丽安",
        "Money": "4",
        "SkillName": "星弦高落：",
        "SkillState": "奥瑞利安索尔在沿直线喷吐出一道纯净的星火，对敌人造成伤害。",
        "Injury": "技能伤害：250 /500 / 750",
        "Relation": "法师",
        "Race": "龙族",
        "HIA": "images/yxtx/11.png",
        "HeroImg": "images/yxyk/11.jpg"
    },
    {
        "HeroNumber": 50,
        "HeroName": "死亡颂唱者",
        "Heroicpainting": "卡尔萨斯",
        "Money": "5",
        "SkillName": "安魂曲：",
        "SkillState": "在较长的吟唱之后，卡尔萨斯对几名随机敌人造成伤害。",
        "Injury": "技能伤害：350 / 600 / 850技能目标：5 / 7 / 9",
        "Relation": "法师",
        "Race": "暗影",
        "HIA": "images/yxtx/33.png",
        "HeroImg": "images/yxyk/33.jpg"
    },
    {
        "HeroNumber": 51,
        "HeroName": "虚空行者",
        "Heroicpainting": "卡萨丁",
        "Money": "1",
        "SkillName": "虚空之刃：",
        "SkillState": "卡萨丁的攻击会偷取敌人的法力值，并将其转化为护盾。",
        "Injury": "技能效果：20 / 40 / 60",
        "Relation": "法师",
        "Race": "虚空",
        "HIA": "images/yxtx/42.png",
        "HeroImg": "images/yxyk/42.jpg"
    },
    {
        "HeroNumber": 52,
        "HeroName": "九尾妖狐",
        "Heroicpainting": "阿狸",
        "Money": "2",
        "SkillName": "欺诈宝珠：",
        "SkillState": "阿狸沿直线发射出一枚宝珠随后将其收回，对其穿越的敌人造成伤害。",
        "Injury": "技能伤害：100 / 200 / 300",
        "Relation": "法师",
        "Race": "狂野",
        "HIA": "images/yxtx/47.png",
        "HeroImg": "images/yxyk/47.jpg"
    },
    {
        "HeroNumber": 53,
        "HeroName": "仙灵女巫",
        "Heroicpainting": "璐璐",
        "Money": "2",
        "SkillName": "狂野生长：",
        "SkillState": "璐璐为一名军提供额外的生命值并将其周围的敌人击飞",
        "Injury": "生命加成：300 /400 /500",
        "Relation": "法师",
        "Race": "约德尔人",
        "HIA": "images/yxtx/51.png",
        "HeroImg": "images/yxyk/51.jpg"
    },
    {
        "HeroNumber": 54,
        "HeroName": "邪恶小法师",
        "Heroicpainting": "维迦",
        "Money": "3",
        "SkillName": " 能量爆裂：",
        "SkillState": "维迦用魔法能力引爆一名敌人，对其造成伤害。如果目标的星阶低于维迦，法术会立刻将其击杀",
        "Injury": "技能伤害： 300 /550 / 800低星目标伤害：19999",
        "Relation": "法师",
        "Race": "约德尔人",
        "HIA": "images/yxtx/52.png",
        "HeroImg": "images/yxyk/52.jpg"
    },
    {
        "HeroNumber": 55,
        "HeroName": "卡牌大师",
        "Heroicpainting": "崔斯特",
        "Money": "2",
        "SkillName": "选牌：",
        "SkillState": "崔斯特随机扔出一张卡牌，不同的卡牌会有不同的效果。红牌对目标与周围单位造成伤害；黄牌造成眩晕效果；蓝牌恢复自身与周围友军法力。",
        "Injury": "红牌伤害：150/250/350\n黄牌眩晕时间：2/3/4\n蓝牌法力恢复：20/35/50",
        "Relation": "法师",
        "Race": "海盗",
        "HIA": "images/yxtx/54.png",
        "HeroImg": "images/yxyk/54.jpg"
    },
    {
        "HeroNumber": 56,
        "HeroName": "屠龙勇士",
        "Heroicpainting": "潘森",
        "Money": "5",
        "SkillName": "大荒星陨：",
        "SkillState": "潘森腾跃至空中，然后俯冲向距离最远的敌人，将其晕眩。沿途的敌人会受到相当于他们最大生命值的魔法伤害。随后他们会燃烧，在10秒里持续受到额外的真实伤害",
        "Injury": "眩晕：4/6/8 最大伤害：15%/30%/45%",
        "Relation": "护卫",
        "Race": "龙族",
        "HIA": "images/yxtx/1.png",
        "HeroImg": "images/yxyk/1.jpg"
    },
    {
        "HeroNumber": 57,
        "HeroName": "虚空之女",
        "Heroicpainting": "卡莎",
        "Money": "5",
        "SkillName": "猎手本能：",
        "SkillState": "卡莎冲到距离最远的敌方单位旁边",
        "Injury": "自身获得(300/600/900)生命值的护盾并获得(30%/60%/90%)攻击速度，持续3秒。",
        "Relation": "游侠/刺客",
        "Race": "虚空",
        "HIA": "images/yxtx/2.png",
        "HeroImg": "images/yxyk/2.jpg"
    }
];